### ISSUE TITLE
Every release variant crash using Android 11

### ISSUE THREAD

**Issue by chitao1234** [WangDaYeeeeee/GeometricWeather#209]
device:oneplus 7
system:derpfest(类AOSP)

crash after 0.5-2 seconds of launching app.
debug variant runs normally, only crashing on release variant.

<details>
<summary>crash log (github release)</summary>

```
time: 1618014851235
msg: java.lang.IllegalArgumentException: Remote stack trace:
	at com.android.server.notification.PreferencesHelper.createNotificationChannel(PreferencesHelper.java:917)
	at com.android.server.notification.NotificationManagerService$10.createNotificationChannelsImpl(NotificationManagerService.java:3353)
	at com.android.server.notification.NotificationManagerService$10.createNotificationChannels(NotificationManagerService.java:3374)
	at android.app.INotificationManager$Stub.onTransact(INotificationManager.java:1519)
	at android.os.Binder.execTransactInternal(Binder.java:1154)

stacktrace: d.b.z.d: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.IllegalArgumentException: Invalid importance level
	at d.b.b0.b.a$c0.a(Functions.java:1)
	at d.b.b0.b.a$c0.accept(Functions.java:1)
	at d.b.b0.d.o.onError(LambdaObserver.java:3)
	at d.b.b0.e.d.n0$a.onError(ObservableDoOnEach.java:7)
	at d.b.b0.e.d.n0$a.onNext(ObservableDoOnEach.java:6)
	at d.b.b0.e.d.c2$a.drainNormal(ObservableObserveOn.java:8)
	at d.b.b0.e.d.c2$a.run(ObservableObserveOn.java:3)
	at d.b.x.b.b$b.run(HandlerScheduler.java:1)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7661)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.IllegalArgumentException: Invalid importance level
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2377)
	at android.os.Parcel.createException(Parcel.java:2357)
	at android.os.Parcel.readException(Parcel.java:2340)
	at android.os.Parcel.readException(Parcel.java:2282)
	at android.app.INotificationManager$Stub$Proxy.createNotificationChannels(INotificationManager.java:3765)
	at android.app.NotificationManager.createNotificationChannels(NotificationManager.java:832)
	at android.app.NotificationManager.createNotificationChannel(NotificationManager.java:820)
	at androidx.core.app.j.c(NotificationManagerCompat.java:2)
	at wangdaye.com.geometricweather.n.c.o.d.D(NormalNotificationIMP.java:31)
	at wangdaye.com.geometricweather.n.a.m(NotificationHelper.java:2)
	at wangdaye.com.geometricweather.background.polling.services.permanent.update.ForegroundNormalUpdateService.h(ForegroundNormalUpdateService.java:2)
	at wangdaye.com.geometricweather.background.polling.services.basic.UpdateService.a(UpdateService.java:1)
	at wangdaye.com.geometricweather.i.a.d$c.c(PollingUpdateHelper.java:4)
	at wangdaye.com.geometricweather.i.a.d$c.a(PollingUpdateHelper.java:4)
	at wangdaye.com.geometricweather.i.a.d$c.b(PollingUpdateHelper.java:9)
	at wangdaye.com.geometricweather.i.a.d.k(PollingUpdateHelper.java:6)
	at wangdaye.com.geometricweather.i.a.d.b(PollingUpdateHelper.java:1)
	at wangdaye.com.geometricweather.i.a.d$c.c(PollingUpdateHelper.java:2)
	at wangdaye.com.geometricweather.i.a.d$c.a(PollingUpdateHelper.java:4)
	at wangdaye.com.geometricweather.i.a.d$c.b(PollingUpdateHelper.java:9)
	at wangdaye.com.geometricweather.i.a.d.k(PollingUpdateHelper.java:6)
	at wangdaye.com.geometricweather.i.a.d.h(PollingUpdateHelper.java:2)
	at wangdaye.com.geometricweather.i.a.d.i(Unknown Source:0)
	at wangdaye.com.geometricweather.i.a.b.a(Unknown Source:4)
	at wangdaye.com.geometricweather.j.g.e.j.i(AsyncHelper.java:1)
	at wangdaye.com.geometricweather.j.g.e.c.accept(Unknown Source:4)
	at d.b.b0.e.d.n0$a.onNext(ObservableDoOnEach.java:2)
	... 10 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.notification.PreferencesHelper.createNotificationChannel(PreferencesHelper.java:917)
	at com.android.server.notification.NotificationManagerService$10.createNotificationChannelsImpl(NotificationManagerService.java:3353)
	at com.android.server.notification.NotificationManagerService$10.createNotificationChannels(NotificationManagerService.java:3374)
	at android.app.INotificationManager$Stub.onTransact(INotificationManager.java:1519)
	at android.os.Binder.execTransactInternal(Binder.java:1154)
```

</details>

**Comment by RemyL** [comment]
I get no crash with F-droid variant from github
With AOSP 11 and arrowOS on xiaomi MI9T
