### ISSUE TITLE
WorkerFactory: Could not instantiate wangdaye.com.geometricweather.background.polling.work.worker.NormalUpdateWorker

### ISSUE THREAD

**Issue by RJSDevel** [WangDaYeeeeee/GeometricWeather#232]
Worker can't instance when start app

2021-05-17 16:01:20.830 20324-22035/wangdaye.com.geometricweather E/WM-WorkerFactory: Could not instantiate wangdaye.com.geometricweather.background.polling.work.worker.NormalUpdateWorker
    java.lang.NoSuchMethodException: wangdaye.com.geometricweather.background.polling.work.worker.NormalUpdateWorker.<init> [class android.content.Context, class androidx.work.WorkerParameters]
        at java.lang.Class.getConstructor0(Class.java:2332)
        at java.lang.Class.getDeclaredConstructor(Class.java:2170)
        at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:95)
        at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:244)
        at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:136)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
2021-05-17 16:01:20.832 20324-22035/wangdaye.com.geometricweather E/WM-WorkerWrapper: Could not create Worker wangdaye.com.geometricweather.background.polling.work.worker.NormalUpdateWorker

**Comment by RJSDevel** [comment]
it was because I has updated  to   implementation "androidx.work:work-runtime:2.6.0-alpha02"
