### ISSUE TITLE
"missing onError handler" crash after upgrade to 3.100

### ISSUE THREAD

**Issue by gbakeman** [WangDaYeeeeee/GeometricWeather#333]
After upgrading from .013 to .100 on F-Droid, the app repeatedly crashes with the following stacktrace. Clearing data appears to have cleared the error as well.

`
FATAL EXCEPTION: main
Process: wangdaye.com.geometricweather, PID: 11718
io.reactivex.exceptions.d: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.n.g, parameter district
	at e5.a$f0.a(Functions.java:1)
	at e5.a$f0.accept(Functions.java:1)
	at io.reactivex.internal.observers.o.onError(LambdaObserver.java:3)
	at io.reactivex.internal.operators.observable.n0$a.onError(ObservableDoOnEach.java:7)
	at io.reactivex.internal.operators.observable.c2$a.checkTerminated(ObservableObserveOn.java:11)
	at io.reactivex.internal.operators.observable.c2$a.drainNormal(ObservableObserveOn.java:3)
	at io.reactivex.internal.operators.observable.c2$a.run(ObservableObserveOn.java:3)
	at b5.b$b.run(HandlerScheduler.java:1)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6898)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.n.g, parameter district
	at wangdaye.com.geometricweather.common.basic.models.Location.<init>(Unknown Source:27)
	at m7.f.a(LocationEntityGenerator.java:1)
	at m7.f.d(LocationEntityGenerator.java:3)
	at j7.e.t(DatabaseHelper.java:11)
	at k6.e.h(PollingUpdateHelper.java:1)
	at k6.e.a(Unknown Source:0)
	at k6.d.a(Unknown Source:2)
	at d7.i.o(AsyncHelper.java:1)
	at d7.i.g(Unknown Source:0)
	at d7.f.a(Unknown Source:2)
	at io.reactivex.internal.operators.observable.b0.subscribeActual(ObservableCreate.java:3)
	at io.reactivex.l.subscribe(Observable.java:14)
	at io.reactivex.internal.operators.observable.j3$b.run(ObservableSubscribeOn.java:1)
	at io.reactivex.t$a.run(Scheduler.java:2)
	at io.reactivex.internal.schedulers.m.run(ScheduledRunnable.java:2)
	at io.reactivex.internal.schedulers.m.call(ScheduledRunnable.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
FATAL EXCEPTION: main
Process: wangdaye.com.geometricweather, PID: 12650
io.reactivex.exceptions.d: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.n.g, parameter district
	at e5.a$f0.a(Functions.java:1)
	at e5.a$f0.accept(Functions.java:1)
	at io.reactivex.internal.observers.o.onError(LambdaObserver.java:3)
	at io.reactivex.internal.operators.observable.n0$a.onError(ObservableDoOnEach.java:7)
	at io.reactivex.internal.operators.observable.c2$a.checkTerminated(ObservableObserveOn.java:11)
	at io.reactivex.internal.operators.observable.c2$a.drainNormal(ObservableObserveOn.java:3)
	at io.reactivex.internal.operators.observable.c2$a.run(ObservableObserveOn.java:3)
	at b5.b$b.run(HandlerScheduler.java:1)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6898)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.n.g, parameter district
	at wangdaye.com.geometricweather.common.basic.models.Location.<init>(Unknown Source:27)
	at m7.f.a(LocationEntityGenerator.java:1)
	at m7.f.d(LocationEntityGenerator.java:3)
	at j7.e.t(DatabaseHelper.java:11)
	at k6.e.h(PollingUpdateHelper.java:1)
	at k6.e.a(Unknown Source:0)
	at k6.d.a(Unknown Source:2)
	at d7.i.o(AsyncHelper.java:1)
	at d7.i.g(Unknown Source:0)
	at d7.f.a(Unknown Source:2)
	at io.reactivex.internal.operators.observable.b0.subscribeActual(ObservableCreate.java:3)
	at io.reactivex.l.subscribe(Observable.java:14)
	at io.reactivex.internal.operators.observable.j3$b.run(ObservableSubscribeOn.java:1)
	at io.reactivex.t$a.run(Scheduler.java:2)
	at io.reactivex.internal.schedulers.m.run(ScheduledRunnable.java:2)
	at io.reactivex.internal.schedulers.m.call(ScheduledRunnable.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
`

**Comment by MichailiK** [comment]
Clearing app data has not stopped the crashes in my case, and is making Geometric Weather quite... unusable.

![Screenshot_20220713-160854](https://user-images.githubusercontent.com/39029839/178754275-abbdc54f-afac-4de4-91aa-b1f311e136b2.png)

If needed, I'd gladly help in fixing this issue, in the meantime, I'll have to stick to the older versions.

**Comment by papjul** [comment]
Do you mean the app is crashing right after clearing app data (not cache) or that the app is crashing after your clear app data and add back your location?

I'm asking because the log seems to hint towards a location issue.

Can you specify if you have a custom ROM, microG or anything that could have a missing support?

**Comment by MichailiK** [comment]
I use CalyxOS 3.7.0 with microG version `0.2.24.214816-25 (4b20f8b)`

I just read my exception more carefully (which I should've done earlier, my apologies) & noticed I have a different bug. It turns out my crashes are caused by the hourly trend widget. After removing the widget from my home screen, Geometric Weather has stopped crashing for me.

<details>
<summary>My stacktrace</summary>

```
FATAL EXCEPTION: main
Process: wangdaye.com.geometricweather, PID: 9529
io.reactivex.exceptions.d: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | android.view.InflateException: Binary XML file line #2 in wangdaye.com.geometricweather:layout/widget_trend_hourly: Binary XML file line #2 in wangdaye.com.geometricweather:layout/widget_trend_hourly: Error inflating class <unknown>
 at e5.a$f0.a(Unknown Source:2)
 at e5.a$f0.accept(Unknown Source:2)
 at io.reactivex.internal.observers.o.onError(LambdaObserver.java:3)
 at io.reactivex.internal.operators.observable.c2$a.checkTerminated(ObservableObserveOn.java:11)
 at io.reactivex.internal.operators.observable.c2$a.drainNormal(ObservableObserveOn.java:3)
 at io.reactivex.internal.operators.observable.c2$a.run(ObservableObserveOn.java:3)
 at b5.b$b.run(HandlerScheduler.java:1)
 at android.os.Handler.handleCallback(Handler.java:938)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:7870)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: android.view.InflateException: Binary XML file line #2 in wangdaye.com.geometricweather:layout/widget_trend_hourly: Binary XML file line #2 in wangdaye.com.geometricweather:layout/widget_trend_hourly: Error inflating class <unknown>
Caused by: android.view.InflateException: Binary XML file line #2 in wangdaye.com.geometricweather:layout/widget_trend_hourly: Error inflating class <unknown>
Caused by: java.lang.reflect.InvocationTargetException
 at java.lang.reflect.Constructor.newInstance0(Native Method)
 at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
 at android.view.LayoutInflater.createView(LayoutInflater.java:858)
 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
 at android.view.LayoutInflater.inflate(LayoutInflater.java:663)
 at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
 at d8.k.C(HourlyTrendWidgetIMP.java:16)
 at d8.k.E(HourlyTrendWidgetIMP.java:3)
 at d8.k.F(HourlyTrendWidgetIMP.java:8)
 at d8.k.H(Unknown Source:0)
 at d8.k.A(Unknown Source:0)
 at d8.j.run(Unknown Source:4)
 at e7.i.q(Unknown Source:0)
 at e7.i.d(Unknown Source:0)
 at e7.g.a(Unknown Source:2)
 at io.reactivex.internal.operators.observable.b0.subscribeActual(ObservableCreate.java:3)
 at io.reactivex.l.subscribe(Observable.java:14)
 at io.reactivex.internal.operators.observable.j3$b.run(Unknown Source:6)
 at io.reactivex.t$a.run(Scheduler.java:2)
 at io.reactivex.internal.schedulers.m.run(ScheduledRunnable.java:2)
 at io.reactivex.internal.schedulers.m.call(Unknown Source:0)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at java.lang.Thread.run(Thread.java:920)
Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 3: TypedValue{t=0x2/d=0x7f0400ff a=5}
 at android.content.res.TypedArray.getColorStateList(TypedArray.java:598)
 at w3.c.a(MaterialResources.java:4)
 at w3.d.<init>(TextAppearance.java:6)
 at d7.a.i(Unknown Source:2)
 at wangdaye.com.geometricweather.remoteviews.trend.TrendLinearLayout.c(TrendLinearLayout.java:6)
 at wangdaye.com.geometricweather.remoteviews.trend.TrendLinearLayout.<init>(TrendLinearLayout.java:14)
 ... 27 more
```

</details>

I apologize for noticing just now. Shall I create a new issue?

**Comment by papjul** [comment]
I thought that "clear app data" would have already delete any widget, but I could reproduce it was not the case. Crash while upgrading from v3.013 to 3.100+ while having a widget is a known issue and can be solved by deleting the widget and adding it back.

**Comment by MichailiK** [comment]
Unfortunately, I still experience issues when attempting to add the hourly widget.

https://user-images.githubusercontent.com/39029839/178812333-4e8c5009-72a2-4c77-88ef-09bfb99977c4.mp4

**Comment by papjul** [comment]
I can reproduce but with a silent crash (no widget is added). You can open a new issue saying the Hourly Trend widget doesn't work, with this video ;)
