### ISSUE TITLE
Crash on startup after upgrade to fdroid 3.100 - java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.n.g, parameter district

### ISSUE THREAD

**Issue by winny-** [WangDaYeeeeee/GeometricWeather#348]
Included some log context.  See also #333.  Can confirm, like in the other issue, clearing data fixes the crashing.

```
06-14 21:01:39.735  1737  1761 I WindowManager:   SURFACE show Surface(name=Splash Screen wangdaye.com.geometricweather)/@0x9fcea14 on display:0: Splash Screen wangdaye.com.geometricweather
06-14 21:01:39.771  1737  2218 I WindowManager: Window drawn AppWindowToken{3f7d383 token=Token{125a32 ActivityRecord{6a3223d u0 fr.neamar.kiss/.MainActivity t355}}}
06-14 21:01:39.971   749  1325 I netd    : firewallSetUidRule(2, 10233, 2) <0.05ms>
06-14 21:01:39.972  1737  2230 D ConnectivityService: Blocked status changed to true for 10233(5493) on netId 110
06-14 21:01:40.038 17521 17521 W IInputConnectionWrapper: getExtractedText on inactive InputConnection
06-14 21:01:40.049 17521 17521 W IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
06-14 21:01:40.053 14564 14564 E FullInputEventModel: selectionUpdated event aborted: ji1: Could not create selection changed event (class ji1)
06-14 21:01:40.177 19148 19148 D NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: false
06-14 21:01:40.287 19148 19148 D AndroidRuntime: Shutting down VM
06-14 21:01:40.288 19148 19148 E AndroidRuntime: FATAL EXCEPTION: main
06-14 21:01:40.288 19148 19148 E AndroidRuntime: Process: wangdaye.com.geometricweather, PID: 19148
06-14 21:01:40.288 19148 19148 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{wangdaye.com.geometricweather/wangdaye.com.geometricweather.main.MainActivity}: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.n.g, parameter district
06-14 21:01:40.288 19148 19148 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3455)
06-14 21:01:40.288 19148 19148 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3598)
06-14 21:01:40.288 19148 19148 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
06-14 21:01:40.288 19148 19148 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
06-14 21:01:40.288 19148 19148 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
06-14 21:01:40.288 19148 19148 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2164)
06-14 21:01:40.288 19148 19148 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
06-14 21:01:40.288 19148 19148 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:241)
06-14 21:01:40.288 19148 19148 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7582)
06-14 21:01:40.288 19148 19148 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-14 21:01:40.288 19148 19148 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
06-14 21:01:40.288 19148 19148 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
06-14 21:01:40.288 19148 19148 E AndroidRuntime: Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.n.g, parameter district
06-14 21:01:40.288 19148 19148 E AndroidRuntime: 	at wangdaye.com.geometricweather.common.basic.models.Location.<init>(Unknown Source:27)
06-14 21:01:40.288 19148 19148 E AndroidRuntime: 	at m7.f.a(LocationEntityGenerator.java:1)
06-14 21:01:40.288 19148 19148 E AndroidRuntime: 	at m7.f.d(LocationEntityGenerator.java:3)
06-14 21:01:40.288 19148 19148 E AndroidRuntime: 	at j7.e.t(DatabaseHelper.java:11)
06-14 21:01:40.288 19148 19148 E AndroidRuntime: 	at wangdaye.com.geometricweather.main.t.o(MainActivityRepository.kt:1)
06-14 21:01:40.288 19148 19148 E AndroidRuntime: 	at wangdaye.com.geometricweather.main.MainActivityViewModel.u(MainActivityViewModel.kt:5)
06-14 21:01:40.288 19148 19148 E AndroidRuntime: 	at wangdaye.com.geometricweather.main.MainActivity.x0(MainActivity.kt:3)
06-14 21:01:40.288 19148 19148 E AndroidRuntime: 	at wangdaye.com.geometricweather.main.MainActivity.onCreate(MainActivity.kt:8)
06-14 21:01:40.288 19148 19148 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7822)
06-14 21:01:40.288 19148 19148 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7811)
06-14 21:01:40.288 19148 19148 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1328)
06-14 21:01:40.288 19148 19148 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3430)
06-14 21:01:40.288 19148 19148 E AndroidRuntime: 	... 11 more
06-14 21:01:40.291  1737 19178 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
06-14 21:01:40.291  1737  6106 W ActivityTaskManager:   Force finishing activity wangdaye.com.geometricweather/.main.MainActivity
06-14 21:01:40.294  9291  9368 D MCLOG   : [MC_TriggerHelper] PauseResumeTrigger
06-14 21:01:40.294  1737 19178 W DropBoxManagerService: Dropping: data_app_crash (2332 > 0 bytes)
06-14 21:01:40.298  1737  1768 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
06-14 21:01:40.299 19148 19148 I Process : Sending signal. PID: 19148 SIG: 9
06-14 21:01:40.301  1737  1768 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
06-14 21:01:40.302  9291  9291 D MCLOG   : [MC_Service] onStartcommand()
```

**Comment by inuitviking** [comment]
Can confirm I get this issue as well, or so I assume. Seems to happen almost whenever the app updates its weather data.

**Comment by lightonflux** [comment]
I am also affected by this. Additionally the app uses a lot mobile data when updating in the background. I had the interval set at 1.5h but it used 2GB in less than a month. I assume it is related to this behaviour. So please check your data usage if you are affected.
