### ISSUE TITLE
How can i change ApplicationId?

### ISSUE THREAD

**Issue by tellfa** [WangDaYeeeeee/GeometricWeather#8]
Hi, i want change **ApplicationId** in **gradle.build** , i changed this but when click on run show me this error in **Android Monitor** tab.

How can i change ApplicationId ? 

Error:
`E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: in.nouri.materialweather, PID: 32331
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{in.nouri.materialweather/wangdaye.com.geometricweather.view.activity.MainActivity}: android.view.InflateException: Binary XML file line #51: Could not inflate Behavior subclass in.nouri.materialweather.view.behavior.InkPageIndicatorBehavior
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2726)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2787)
                      at android.app.ActivityThread.-wrap12(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1504)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6247)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
                   Caused by: android.view.InflateException: Binary XML file line #51: Could not inflate Behavior subclass in.nouri.materialweather.view.behavior.InkPageIndicatorBehavior
                   Caused by: java.lang.RuntimeException: Could not inflate Behavior subclass in.nouri.materialweather.view.behavior.InkPageIndicatorBehavior
                      at android.support.design.widget.CoordinatorLayout.parseBehavior(CoordinatorLayout.java:604)
                      at android.support.design.widget.CoordinatorLayout$LayoutParams.<init>(CoordinatorLayout.java:2549)
                      at android.support.design.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:1610)
                      at android.support.design.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:108)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:860)
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                      at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143)
                      at wangdaye.com.geometricweather.view.activity.MainActivity.onCreate(MainActivity.java:120)
                      at android.app.Activity.performCreate(Activity.java:6754)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2679)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2787)
                      at android.app.ActivityThread.-wrap12(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1504)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6247)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
                   Caused by: java.lang.ClassNotFoundException: in.nouri.materialweather.view.behavior.InkPageIndicatorBehavior
                      at java.lang.Class.classForName(Native Method)
                      at java.lang.Class.forName(Class.java:400)
                      at android.support.design.widget.CoordinatorLayout.parseBehavior(CoordinatorLayout.java:596)
                      at android.support.design.widget.CoordinatorLayout$LayoutParams.<init>(CoordinatorLayout.java:2549) 
                      at android.support.design.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:1610) 
                      at android.support.design.widget.CoordinatorLayout.generateLayoutParams(CoordinatorLayout.java:108) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:860) 
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:861) 
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:518) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:426) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:377) 
                      at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284) 
                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143) 
                      at wangdaye.com.geometricweather.view.activity.MainActivity.onCreate(MainActivity.java:120) 
                      at android.app.Activity.performCreate(Activity.java:6754) 
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2679) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2787) 
                      at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1504) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:154) 
                      at android.app.ActivityThread.main(ActivityThread.java:6247) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762) 
                   Caused by: java.lang.ClassNotFoundException: Didn't find class "in.nouri.materialweather.view.behavior.InkPageIndicatorBehavior" on path: DexPathList[[zip file "/data/app/in.nouri.materialweather-2/base.apk"],nativeLibraryDirectories=[/data/app/in.nouri.materialweather-2/lib/arm64, /data/app/in.nouri.materialweather-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
E/AndroidRuntime:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)`

**Comment by tellfa** [comment]
can you help me?

**Comment by WangDaYeeeeee** [comment]
Well, I never try to change applicationId, so I have no idea just like you.

Maybe try to clean project and rebuild ?
